### PR TITLE
bump to 0.7.3

### PR DESCRIPTION
**Pull request by sappelhoff**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sappelhoff** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
@sappelhoff there is really no need to manually bump this, unless dependencies have changed :) the bot will take care of it

**Comment by sappelhoff** [comment]
It's more that I am impatient and the bot will take a couple of hours to update this :wink: 

but I think impatience is also what lead me to do 0.7.0, 0.7.1, 0.7.2, and 0.7.3 all within a too short amount of time :grimacing:

**Comment by hoechenberger** [comment]
Hehehe alright then 😅

**Pull request merged**
