### PR TITLE
Add NumPy pinning and add MNE requirement (to allow reading)

### PR DESCRIPTION
**Pull request by hoechenberger**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@conda-forge-admin, please rerender

**Comment by hoechenberger** [comment]
@sappelhoff WDYT?

**Review by sappelhoff — APPROVED** [review]
Mne is only needed for export, but fine with me to have it in the conda recipe

**Comment by hoechenberger** [comment]
> Mne is only needed for export, but fine with me to have it in the conda recipe

The pybv docs say the exact opposite though?

They say that for,writing, only NumPy is required. And:

> Currently, pybv recommends using MNE-Python for reading BrainVision files.

**Comment by sappelhoff** [comment]
yes, but that's just because the pybv "IO" is really just an "O" at this point, and for "I", we recommend people use MNE-Python. I.e., pybv is NOT a reader, just a writer.

The mne dependency is "private" kind of, because of the new `pybv._export` module that is intended for use within `mne.export`.

Ultimately adding mne as a dependency is thus not needed apart from running the tests, because whenever `pybv._export` is going to be used, it will be from within an env where mne is present anyhow. :-)

**Comment by hoechenberger** [comment]
Ooooh, I see, so then there's actually no need to add MNE as a dependency. I'll close this PR then without merging.

**Pull request closed without merging**
